language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: jarid-portfolio
  api_key:
    secure: DPMRIDpvgx8UqoFWyc61kh0q6Hdf5qnLCShW6VWw84T49GEweuNXzOS1g0qMsnIAS5z2cDjY/pPJlUmFVxrcQrkPasTYvAK78gBuxHfymy/kHz9zHkhodLPzfHBWCqi4UhmTN0jcAEjK/qri1C0SgHQw73O93XZQU+O9tidBf1X/OS1BtgSb+SISUdQyNc1wMwYdT8vslw9+kwvqazCvT+UFvvRpVKkCvmhr2exv29Ulyj7vQy8J1/JC/zZiPKnYHH4o8Oehcsku6RweQmBFTYgWbLG3GT3bLvzMBjYpYnzHnH5eeXbfUIJoFLgiQo82ZK/44Bf+ujF+SaQwk6/s4sHZSgdRqSXwmZ0+Ua9XPNSyFV+n3wVYUuBTRhGoBnoY0+69r0W2Nc6DFymm3ClFdJtVni0fkshcDovV0fw+f0BHSuTAcD36hnlRwc9a8m2CqqoRAeteQCyskxOvOzw7eL43QpZ+AdIMx6UAr40NNtZM3UAICFtriweLs3O5MRZkVDyP48IYPfCtT58TOxKQi4QKkEBP+s7DFcC11um9xJm8fvaMVNVG3sJ2PXOWV31PfVdSQ4x93iycBZnEXNb9ola78BOi5vXAYzuso5iBY+sZ41aAPaxgjN6gEdfP/EdGIgunlJD4N3SFdgR0SortRjSnGQcLTiWI/vRnzvgeFxM=
