language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: jarid-portfolio
  api_key:
    secure: JnFBitPq4cXLxrIrVZSEkg9kIjb7PF94tYD3LC3vuJopPtWUNvS37wytskG5umU0uU4bMEfsaXLwE+YAl8MqtJxlKstgZuD7n2tLtH15Zuz8oHbpcgGLuOQIoN5jcBNJKxM4Ytq9A8L9fDiq97HYzeNuZMhuAzzt50njgih8NmuNkNHnL0OgmExOOPl6GF4GigAdi5l3czLSmMEovrn4kn3Yoc7boyGDrgfzywRHQf1jJqR7eE0ScgT4DKJly/e+xQAoVIoSw5PHNTV5itDhFyi3dFDxZKxb0X0JaCHhnfnGKXgn+wH0m+BdGzvQnkSYKyWiZgOGVagy+P3hfABGo6mo676HF4OgChOwRzi7A/+xhLyDQMBs9pXeQ9uGiNLj/WLcy1PK3TM7USzgDK42eJWH/3eCis7SZND87PKKEZaqHE/YnthuwEgqftkK7SGD1Uj/oLbrRQ3qNsdZ/d+BeLJKyUlXQDMuHfGCD20dt3WyVDmU5LaH1SRnSNNIvAf5e4tEJT7QrvMigKe6drTOCSkc5DQYqqq36p4fgo7tCmpyP6AXBdtN9LlwDEWe4Kh/HxseZ1c1EUnKZLAi3nDE0gcddt5wWS4hYOjntW3dPaDV/GcX9pzALe7Iq8t5rzO9J3gLzKgz8P0lfZsvNdnID9yJH8U3Vf+QRo84DtKh/jI=
